version: '3.8'

services:
  app:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      PGPASSWORD: ${PGPASSWORD}
      DB_NAME: predict_logs_db
      OLLAMA_HOST: ollama:11434
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env 
    healthcheck:
      test: ["CMD", "python", "tests/healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./model.joblib:/app/model.joblib
      - ./scaler.joblib:/app/scaler.joblib

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: predict_logs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d predict_logs_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile.etl
    environment:
      PGPASSWORD: ${PGPASSWORD}
      ETL_INTERVAL: 30
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: