FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
RUN mkdir -p src/etl && touch src/etl/__init__.py

RUN --mount=type=cache,target=/root/.cache/uv \
    pip install uv && \
    uv sync --frozen --no-dev

COPY src/etl/ ./src/etl/

ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "src/etl/etl_service.py"]